//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnemploymentRate
    {
        public int id { get; set; }
        public int date_id { get; set; }
        public int unemployment_rate { get; set; }
    
        public virtual ReportingDate ReportingDate { get; set; }
    }
}
